stages:
  - clean-git-history-checking
  - conventional-commits-linting
  - formatting
  - linting
  - compiling
  - unit-testing


services:
  - docker:dind


variables:
  DOCKER_HOST: tcp://docker:2375
  EARTHLY_EXEC_CMD: "/bin/sh"


image: earthly/earthly:v0.6.22


clean-git-history-checking:
  stage: clean-git-history-checking
  script:
    - earthly --ci +clean-git-history-checking --from "origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}"
  rules:
    - if: $CI_MERGE_REQUEST_ID


conventional-commits-linting:
  stage: conventional-commits-linting
  script:
    - earthly --ci +conventional-commits-linting --from "origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}"
  rules:
    - if: $CI_MERGE_REQUEST_ID


formatting:
  stage: formatting
  script:
    - earthly --ci +check-formatting
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == "master"


linting:
  stage: linting
  script:
    - earthly --ci +linting
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == "master"


compiling:
  stage: compiling
  script:
    - earthly --ci +compiling
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == "master"


unit-testing:
  stage: unit-testing
  script:
    - earthly --ci +unit-testing
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == "master"
