image: archlinux/base

stages:
    - format
    - build

format:
    stage: format 
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S gawk grep --noconfirm
        - pacman -S clang diffutils --noconfirm
    script:
        - for i in $( du -a src/ tests | awk '{print $2}' | grep -i ".c$" ); do
        - clang-format $i > temp.txt
        - cmp $i temp.txt
        - done

build:
    stage: build
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel --noconfirm
        - pacman -S lib32-gcc-libs lib32-glibc --noconfirm 
        - pacman -S make --noconfirm
        - pacman -S cunit --noconfirm
    script:
        - make
        - make test
    artifacts:
        paths:
            - shellcode-generator 
