image: archlinux/base

stages:
    - install_dependencies
    - build
    - test

install_dependencies:
    stage: install_dependencies 
    script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel --noconfirm
        - pacman -S lib32-gcc-libs lib32-glibc --noconfirm 
        - pacman -S make --noconfirm
        - pacman -S cunit --noconfirm

build:
    stage: build
    script:
        - make

test:
    stage: test
    script:
        - make test

